# basic options
title: Justin's-Portfolio
author: Justin Man
email: justinm517@gmail.com
description: A test portolio
twitter_username: thedank27
github_username: justinm517

# Build settings
markdown: kramdown
theme: minima
